<?php

return array(
    'application.components._extend.*',
    'application.components.*',
    'application.components.loader.*',
    'application.components.call.*',
    'application.components.object.*',
    //
    'application.call._extend.*',
    'application.call.*',
    'application.call.account.*',
    'application.call.character.*',
    //
    'application.widgets._extend.*',
    'application.widgets.*',
    //
    'application.models._extend.*',
    'application.models.*',
    //
    'application.forms._extend.*',
    'application.forms.*',
    //
    'application.controllers._extend.*',
    'application.controllers.*',
    //
    'application.controllers.user._extend.*',
    'application.controllers.user.*',
);